accelerator: null
accumulate_grad_batches: null
activation: leakyrelu
amp_backend: native
amp_level: null
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
batch_size: 1024
benchmark: false
check_val_every_n_epoch: 10
checkpoint_callback: null
data_path: ../dataset/PFCN_BiasedMF_embed-sm-[age].pth
default_root_dir: null
detect_anomaly: false
deterministic: false
devices: null
dropout: 0.3
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
fast_dev_run: false
flush_logs_every_n_steps: null
gpus:
- 0
gradient_clip_algorithm: null
gradient_clip_val: null
input_dim: 64
ipus: null
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 24
log_gpu_memory: null
logger: true
lr: 0.001
max_epochs: 300
max_steps: -1
max_time: null
min_epochs: null
min_steps: null
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
output_dim: 7
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: null
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
sst: age
stochastic_weight_avg: false
strategy: null
sync_batchnorm: false
terminate_on_nan: null
tpu_cores: null
track_grad_norm: -1
val_check_interval: 1.0
weight_decay: 0.0001
weights_save_path: null
weights_summary: top
